# Default scoring profile for suricata-rule-scoring

scoring:
  quality:
    base: 0
    min: null
    max: null
  false_positive:
    base: 0
    min: null
    max: null

criteria:
  # =========================================
  # Quality Criteria
  # =========================================

  - id: has_content_match
    name: "Has content match"
    description: "Rule contains at least one content keyword"
    dimension: quality
    weight: 10
    condition:
      field: "options.content"
      operator: "exists"

  - id: has_fast_pattern
    name: "Uses fast_pattern"
    description: "Rule uses fast_pattern for performance"
    dimension: quality
    weight: 5
    condition:
      field: "options.fast_pattern"
      operator: "exists"

  - id: specific_protocol
    name: "Specific protocol"
    description: "Protocol is app-layer specific (not ip/tcp/udp)"
    dimension: quality
    weight: 5
    condition:
      field: "protocol"
      operator: "not_in"
      value: ["ip", "tcp", "udp", "tcp-pkt", "tcp-stream"]

  - id: has_flow_direction
    name: "Has flow keyword"
    description: "Rule specifies flow (established, to_server, etc.)"
    dimension: quality
    weight: 5
    condition:
      field: "options.flow"
      operator: "exists"

  - id: tls_fingerprint
    name: "TLS fingerprint match"
    description: "Rule matches on TLS certificate or JA3 fields"
    dimension: quality
    weight: 15
    condition:
      operator: "any"
      conditions:
        - field: "options.tls.cert_subject"
          operator: "exists"
        - field: "options.tls.cert_serial"
          operator: "exists"
        - field: "options.tls_cert_subject"
          operator: "exists"
        - field: "options.tls_cert_serial"
          operator: "exists"
        - field: "options.tls.cert_fingerprint"
          operator: "exists"
        - field: "options.tls_cert_fingerprint"
          operator: "exists"
        - field: "options.tls.fingerprint"
          operator: "exists"
        - field: "options.ja3.hash"
          operator: "exists"
        - field: "options.ja3_hash"
          operator: "exists"
        - field: "options.ja3s.hash"
          operator: "exists"
        - field: "options.ja3s_hash"
          operator: "exists"
        - field: "options.ja4.hash"
          operator: "exists"

  - id: deep_content
    name: "Deep content inspection"
    description: "Rule has 3+ content matches"
    dimension: quality
    weight: 8
    condition:
      field: "options.content|count"
      operator: "gte"
      value: 3

  - id: pcre_without_content
    name: "PCRE without content prefilter"
    description: "Uses PCRE without content to anchor, hurting performance and quality"
    dimension: quality
    weight: -10
    condition:
      operator: "all"
      conditions:
        - field: "options.pcre"
          operator: "exists"
        - operator: "not"
          condition:
            field: "options.content"
            operator: "exists"

  - id: no_content_match
    name: "No content match"
    description: "Rule has zero content, pcre, or app-layer match keywords"
    dimension: quality
    weight: -10
    condition:
      operator: "all"
      conditions:
        - operator: "not"
          condition:
            field: "options.content"
            operator: "exists"
        - operator: "not"
          condition:
            field: "options.pcre"
            operator: "exists"
        - operator: "not"
          condition:
            field: "options.dns.query"
            operator: "exists"
        - operator: "not"
          condition:
            field: "options.dns_query"
            operator: "exists"
        - operator: "not"
          condition:
            field: "options.tls.cert_subject"
            operator: "exists"
        - operator: "not"
          condition:
            field: "options.tls_cert_subject"
            operator: "exists"
        - operator: "not"
          condition:
            field: "options.http_uri"
            operator: "exists"
        - operator: "not"
          condition:
            field: "options.http_header"
            operator: "exists"
        - operator: "not"
          condition:
            field: "options.http.uri"
            operator: "exists"

  # tiny_payload — requires built-in plugin (see plugins section below)

  - id: content_position_modifiers
    name: "Content position modifiers"
    description: "Rule uses depth, offset, distance, or within to constrain content matching"
    dimension: quality
    weight: 5
    condition:
      operator: "any"
      conditions:
        - field: "options.depth"
          operator: "exists"
        - field: "options.offset"
          operator: "exists"
        - field: "options.distance"
          operator: "exists"
        - field: "options.within"
          operator: "exists"

  - id: has_flowbits
    name: "Uses flowbits"
    description: "Rule uses flowbits for multi-stage/correlated detection"
    dimension: quality
    weight: 5
    condition:
      field: "options.flowbits"
      operator: "exists"

  - id: has_byte_operations
    name: "Byte-level operations"
    description: "Rule uses byte_test, byte_jump, or byte_extract for precise binary parsing"
    dimension: quality
    weight: 8
    condition:
      operator: "any"
      conditions:
        - field: "options.byte_test"
          operator: "exists"
        - field: "options.byte_jump"
          operator: "exists"
        - field: "options.byte_extract"
          operator: "exists"

  - id: has_dsize
    name: "Has dsize constraint"
    description: "Rule constrains payload size with dsize keyword"
    dimension: quality
    weight: 3
    condition:
      field: "options.dsize"
      operator: "exists"

  - id: content_anchoring
    name: "Content anchoring"
    description: "Rule uses startswith or endswith to anchor content in sticky buffers"
    dimension: quality
    weight: 3
    condition:
      operator: "any"
      conditions:
        - field: "options.startswith"
          operator: "exists"
        - field: "options.endswith"
          operator: "exists"

  - id: has_isdataat
    name: "Has isdataat check"
    description: "Rule verifies data exists at a given offset before matching"
    dimension: quality
    weight: 2
    condition:
      field: "options.isdataat"
      operator: "exists"

  - id: bidirectional_rule
    name: "Bidirectional rule"
    description: "Rule uses <> direction, doubling evaluation cost and indicating imprecision"
    dimension: quality
    weight: -5
    condition:
      field: "direction"
      operator: "eq"
      value: "<>"

  - id: any_any_source
    name: "Source is any/any"
    description: "Source address and port are both any"
    dimension: quality
    weight: -3
    condition:
      operator: "all"
      conditions:
        - field: "source_address"
          operator: "eq"
          value: "any"
        - field: "source_port"
          operator: "eq"
          value: "any"

  - id: any_any_dest
    name: "Destination is any/any"
    description: "Destination address and port are both any"
    dimension: quality
    weight: -3
    condition:
      operator: "all"
      conditions:
        - field: "destination_address"
          operator: "eq"
          value: "any"
        - field: "destination_port"
          operator: "eq"
          value: "any"

  # =========================================
  # False-Positive Criteria
  # =========================================

  - id: broad_network_scope
    name: "Broad network scope"
    description: "Both source and destination addresses are any — high FP risk"
    dimension: false_positive
    weight: 8
    condition:
      operator: "all"
      conditions:
        - field: "source_address"
          operator: "eq"
          value: "any"
        - field: "destination_address"
          operator: "eq"
          value: "any"

  - id: any_ports
    name: "Any ports"
    description: "Both source and destination ports are any"
    dimension: false_positive
    weight: 3
    condition:
      operator: "all"
      conditions:
        - field: "source_port"
          operator: "eq"
          value: "any"
        - field: "destination_port"
          operator: "eq"
          value: "any"

  # generic_protocol — requires built-in plugin

  # few_content_matches — requires built-in plugin

  - id: no_flow_state
    name: "No flow state"
    description: "Rule does not specify flow keyword"
    dimension: false_positive
    weight: 3
    condition:
      operator: "not"
      condition:
        field: "options.flow"
        operator: "exists"

  - id: pcre_only
    name: "PCRE-only detection"
    description: "Detection relies solely on PCRE with no content anchoring"
    dimension: false_positive
    weight: 7
    condition:
      operator: "all"
      conditions:
        - field: "options.pcre"
          operator: "exists"
        - operator: "not"
          condition:
            field: "options.content"
            operator: "exists"

  - id: specific_tls_match
    name: "Specific TLS/cert match"
    description: "Rule matches specific TLS attributes (low FP risk)"
    dimension: false_positive
    weight: -10
    condition:
      operator: "any"
      conditions:
        - field: "options.tls.cert_subject"
          operator: "exists"
        - field: "options.tls.cert_serial"
          operator: "exists"
        - field: "options.tls_cert_subject"
          operator: "exists"
        - field: "options.tls_cert_serial"
          operator: "exists"
        - field: "options.tls.cert_fingerprint"
          operator: "exists"
        - field: "options.tls_cert_fingerprint"
          operator: "exists"
        - field: "options.tls.fingerprint"
          operator: "exists"
        - field: "options.ja3.hash"
          operator: "exists"
        - field: "options.ja3_hash"
          operator: "exists"
        - field: "options.ja3s.hash"
          operator: "exists"
        - field: "options.ja3s_hash"
          operator: "exists"
        - field: "options.ja4.hash"
          operator: "exists"

  - id: specific_dns_query
    name: "Specific DNS query match"
    description: "Rule matches specific DNS query content"
    dimension: false_positive
    weight: -8
    condition:
      operator: "any"
      conditions:
        - field: "options.dns.query"
          operator: "exists"
        - field: "options.dns_query"
          operator: "exists"

  - id: scoped_source_address
    name: "Scoped source address"
    description: "Source address uses a network variable or literal instead of any"
    dimension: false_positive
    weight: -1
    condition:
      field: "source_address"
      operator: "neq"
      value: "any"

  - id: scoped_dest_address
    name: "Scoped destination address"
    description: "Destination address uses a network variable or literal instead of any"
    dimension: false_positive
    weight: -1
    condition:
      field: "destination_address"
      operator: "neq"
      value: "any"

  # port_specificity — requires built-in plugin (distinguishes single port vs range)

  - id: multi_content
    name: "Multiple content matches"
    description: "Rule has 3+ content matches (higher specificity)"
    dimension: false_positive
    weight: -5
    condition:
      field: "options.content|count"
      operator: "gte"
      value: 3

  - id: has_threshold
    name: "Has threshold/detection_filter"
    description: "Rule includes threshold or detection_filter to limit alerts"
    dimension: false_positive
    weight: -5
    condition:
      operator: "any"
      conditions:
        - field: "options.threshold"
          operator: "exists"
        - field: "options.detection_filter"
          operator: "exists"

  - id: positioned_content
    name: "Position-constrained content"
    description: "Content matching constrained by depth/offset/distance/within (lower FP)"
    dimension: false_positive
    weight: -5
    condition:
      operator: "any"
      conditions:
        - field: "options.depth"
          operator: "exists"
        - field: "options.offset"
          operator: "exists"
        - field: "options.distance"
          operator: "exists"
        - field: "options.within"
          operator: "exists"

  - id: byte_operations_precision
    name: "Byte-level precision"
    description: "Byte operations (byte_test/byte_jump/byte_extract) provide precise matching"
    dimension: false_positive
    weight: -5
    condition:
      operator: "any"
      conditions:
        - field: "options.byte_test"
          operator: "exists"
        - field: "options.byte_jump"
          operator: "exists"
        - field: "options.byte_extract"
          operator: "exists"

  - id: dsize_constraint
    name: "Payload size constraint"
    description: "dsize constrains packet size, reducing coincidental matches"
    dimension: false_positive
    weight: -3
    condition:
      field: "options.dsize"
      operator: "exists"

  - id: has_bsize
    name: "Buffer size constraint"
    description: "bsize constrains sticky buffer size, reducing coincidental matches"
    dimension: false_positive
    weight: -3
    condition:
      field: "options.bsize"
      operator: "exists"

  - id: bidirectional_fp
    name: "Bidirectional FP risk"
    description: "Bidirectional rule evaluates both directions, increasing FP chance"
    dimension: false_positive
    weight: 5
    condition:
      field: "direction"
      operator: "eq"
      value: "<>"

  # long_content_match — requires built-in plugin (computes total content bytes)
  # flowbits_isset — requires built-in plugin (inspects flowbits value)
  # ip_ioc_fp — requires built-in plugin (extends IP IoC check to FP dimension)
  # single_content_http_method — requires built-in plugin (inspects content values)

plugins:
  - id: long_content_match
    name: "Long content match"
    callable: "suricata_rule_scoring.plugin:builtin_long_content_match"

  - id: tiny_payload
    name: "Tiny payload match"
    callable: "suricata_rule_scoring.plugin:builtin_tiny_payload"

  - id: few_content_matches
    name: "Few content matches"
    callable: "suricata_rule_scoring.plugin:builtin_few_content_matches"

  - id: ip_ioc_rule
    name: "IP-based IoC rule"
    callable: "suricata_rule_scoring.plugin:builtin_ip_ioc_rule"

  - id: rule_age
    name: "Rule age"
    callable: "suricata_rule_scoring.plugin:builtin_rule_age"

  - id: generic_protocol
    name: "Generic protocol"
    callable: "suricata_rule_scoring.plugin:builtin_generic_protocol"

  - id: flowbits_isset
    name: "Flowbits isset (multi-stage)"
    callable: "suricata_rule_scoring.plugin:builtin_flowbits_isset"

  - id: ip_ioc_fp
    name: "IP IoC (low FP)"
    callable: "suricata_rule_scoring.plugin:builtin_ip_ioc_fp"

  - id: single_content_http_method
    name: "Single content HTTP method"
    callable: "suricata_rule_scoring.plugin:builtin_single_content_http_method"

  - id: port_specificity
    name: "Port specificity"
    callable: "suricata_rule_scoring.plugin:builtin_port_specificity"
